import { Component } from 'react';
class Users extends Component {
    static Columns = [
        {
            id: 'id',
            numeric: true,
            disablePadding: false,
            label: 'ID',
            type: 'integer',
            columnVisible: false,
            size: 'small',
            editable: false,
        },
        {
            id: 'name',
            numeric: false,
            disablePadding: false,
            label: 'Nume',
            type: 'text',
            columnVisible: true,
            size: 'small',
            editable: true,
        },
        {
            id: 'username',
            numeric: false,
            disablePadding: false,
            label: 'Utilizator',
            type: 'text',
            columnVisible: true,
            size: 'small',
            editable: true,
        },
        {
            id: 'authEmailConfirmedLink',
            numeric: false,
            disablePadding: false,
            label: 'Link de confirmare email',
            type: 'text',
            columnVisible: false,
            size: 'small',
            editable: true,
        },
        {
            id: 'authPasswordResetLink',
            numeric: false,
            disablePadding: false,
            label: 'Link de resetarea parola',
            type: 'text',
            columnVisible: true,
            size: 'small',
            editable: true,
        },
        {
            id: 'phone',
            numeric: false,
            disablePadding: false,
            label: 'Telefon',
            type: 'text',
            columnVisible: true,
            size: 'small',
            editable: true,
        },
        {
            id: 'password',
            numeric: false,
            disablePadding: false,
            label: 'Parola',
            type: 'text',
            columnVisible: true,
            size: 'regular',
            editable: true,
        },
        {
            id: 'suspended',
            numeric: true,
            disablePadding: false,
            label: 'Suspendat',
            type: 'boolean',
            columnVisible: true,
            size: 'regular',
            editable: true,
        },
        {
            id: 'enabled',
            numeric: true,
            disablePadding: false,
            label: 'Activat',
            type: 'boolean',
            columnVisible: true,
            size: 'regular',
            editable: true,
        },
        {
            id: 'authEmailConfirmed',
            numeric: true,
            disablePadding: false,
            label: 'Email confirmat',
            type: 'boolean',
            columnVisible: true,
            size: 'regular',
            editable: true,
        },
        {
            id: 'missedPasswordCounter',
            numeric: true,
            disablePadding: false,
            label: 'Nr. greșeli pass.',
            type: 'boolean',
            columnVisible: true,
            size: 'regular',
            editable: true,
        },
        {
            id: 'idLanguages',
            numeric: true,
            disablePadding: false,
            label: 'Limbă',
            type: 'select',
            selectApiName: "languages",
            selectApiParameter: undefined, // the name of the column from the current object that will be used in the selectApiName query
            selectApiPath: "languagesList",
            selectApiColumnName: "name",
            selectApiColumnType: "text",
            columnVisible: true,
            size: 'regular',
            editable: true,
            notNull: true,
            mandatory: true,
        },
        {
            id: 'idCountries',
            numeric: true,
            disablePadding: false,
            label: 'Tară',
            type: 'select',
            selectApiName: "countries",
            selectApiParameter: undefined, // the name of the column from the current object that will be used in the selectApiName query
            selectApiPath: "countriesList",
            selectApiColumnName: "name",
            selectApiColumnType: "text",
            columnVisible: true,
            size: 'regular',
            editable: true,
            notNull: true,
            mandatory: true,
        },
    ];
    static DEFAULT_ORDER = 'asc';
    static DEFAULT_ORDER_BY = 'name';
    static DEFAULT_ROWS_PER_PAGE = 5;
    static apiName = "users";
    static apiEditName = "users";
    static apiDeleteName = "users";
    static apiPath = "usersList";
}
export default Users;
